<a href="https://colab.research.google.com/github/ruraul/fundamentos_neuronales/blob/main/dimensiones_tensores_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

Scalar


In [6]:
x=np.array(24)
print(x.shape)
x.ndim

()


0

Vector


In [13]:
x = np.array([3,461,62,672,3335,1452,4])
print(x.shape)
x.ndim

(7,)


1

matrix


In [23]:
x = np.array([[[422,422],
              [24,351]],
              [[422,422],
              [24,351]],
              [[422,422],
              [24,351]]])
print(x.shape)
x.ndim

(3, 2, 2)


3

Reshape


In [26]:
x = np.array([[0,1],
          [2,3],
          [4,5],
          [6,7],
          [8,9],
          [10,11],
          [12,13],
          ])
x.shape

(7, 2)

In [27]:
x.reshape(14,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [28]:
np.transpose(x)

array([[ 0,  2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11, 13]])

In [29]:
x.T

array([[ 0,  2,  4,  6,  8, 10, 12],
       [ 1,  3,  5,  7,  9, 11, 13]])